Pendle strategy
rodeofi/rodeo pull request #24
Opened 2023-06-12 16:40 UTC by smak0v

2023-06-13 18:29 UTC, farmercarlton requested changes
Few pretty minor tweaks and we're good to try this out in prod :) 🥇

2023-06-13 18:29 UTC, farmercarlton commented on contracts/src/strategies/StrategyPendleCamelot.sol
> +        if (rate < strategyHelper.value(ast, bal) * (10000 - slp) / 10000) revert PriceSlipped();
Again, here `rate` if for the whole farm and not scaled to this amount of lp / shares

2023-06-13 18:29 UTC, farmercarlton commented on contracts/src/strategies/StrategyPendleCamelot.sol
> +            address(pr), removePendleLiquidity((sha * totalManagedAssets()) / totalShares, address(pr))
It's a bit confusing to the reader to be calling transfer before the call to `removePendleLiquidity` as we don't know where the tokens are coming from, we should put each on their own line

2023-06-13 18:29 UTC, farmercarlton commented on contracts/src/strategies/StrategyPendleCamelot.sol
> +    function addPendleLiquidity(uint256 amt, address ast) private returns (uint256 netLpOut) {
I think it's a bit confusing to the reader that we are taking in `ast` when it'll always be `pair` I think it would be better to drop the param and do an other sload of `pair` so it's clear that that's the token we are dealing with here

2023-06-13 18:29 UTC, farmercarlton commented on contracts/src/strategies/StrategyPendleCamelot.sol
> +        return pairPrice * tma * lpRate / 1e36;
Just to avoid overfows on large numbers maybe we are better off doing `(pairPrice * lpRate / 1e18) * tma / 1e18)`

2023-06-13 18:29 UTC, farmercarlton commented on contracts/src/strategies/StrategyPendleCamelot.sol
> +        return 2 * ((sqrt(reserve0 * reserve1) * sqrt(price0 * price1)) / pr.totalSupply());
Cool, happy to see that you are reusing the manipulation resistant univ2 lp token valuing 😎

2023-06-13 18:29 UTC, farmercarlton commented on contracts/src/test/StrategyPendleCamelot.t.sol
> +        uint256 sha2 = str2.totalShares();
This is logic that's done by `Strategy.sol` let's maybe remove that assertion and asset that the market lp tokens were properly moved as that's what matters, or that `rate(totalShares())` is the same at least

2023-06-14 06:20 UTC, smak0v commented on contracts/src/strategies/StrategyPendleCamelot.sol
> +
Sure. Done.

2023-06-14 06:24 UTC, smak0v commented on contracts/src/strategies/StrategyPendleCamelot.sol
> +        if (newTargetAsset == address(0)) revert WrongTargetAsset();
Done.

2023-06-14 06:30 UTC, smak0v commented on contracts/src/strategies/StrategyPendleCamelot.sol
> +        return 2 * ((sqrt(reserve0 * reserve1) * sqrt(price0 * price1)) / pr.totalSupply());
Thank you)

2023-06-14 06:32 UTC, smak0v commented on contracts/src/strategies/StrategyPendleCamelot.sol
> +        return pairPrice * tma * lpRate / 1e36;
Done.

2023-06-14 06:36 UTC, smak0v commented on contracts/src/strategies/StrategyPendleCamelot.sol
> +    function addPendleLiquidity(uint256 amt, address ast) private returns (uint256 netLpOut) {
Done.

2023-06-14 06:48 UTC, smak0v commented on contracts/src/strategies/StrategyPendleCamelot.sol
> +            address(pr), removePendleLiquidity((sha * totalManagedAssets()) / totalShares, address(pr))
Done.

I did this when I was getting a "stack too deep" error and forgot to refactor here when refactoring.

2023-06-14 07:03 UTC, smak0v commented on contracts/src/strategies/StrategyPendleCamelot.sol
> +        if (valueLiquidity() < strategyHelper.value(ast, amt) * (10000 - slp) / 10000) revert PriceSlipped();
Done.
I decided to add an `amt` parameter to the `valueLiquidity()` method because we are calling it in 3 different places and it looks better than to scale its result in 3 different places as for me.

2023-06-14 07:03 UTC, smak0v commented on contracts/src/strategies/StrategyPendleCamelot.sol
> +        if (rate < strategyHelper.value(ast, bal) * (10000 - slp) / 10000) revert PriceSlipped();
Done.
I decided to add an `amt` parameter to the `valueLiquidity()` method because we are calling it in 3 different places and it looks better than to scale its result in 3 different places as for me.

2023-06-14 07:14 UTC, smak0v commented on contracts/src/test/StrategyPendleCamelot.t.sol
> +        uint256 sha2 = str2.totalShares();
Done

2023-06-14 11:25 UTC, merged