feat/rod-10 position GLP
rodeofi/rodeo pull request #4
Opened 2023-03-24 10:46 UTC by voytenko-d

- add func currentPrice to StrategyPlutusPlvGlp
- fetch strategies data
- show current price
- show liquidated price

2023-03-24 17:46 UTC, farmercarlton requested changes

2023-03-24 17:46 UTC, farmercarlton commented on contracts/src/StrategyPlutusPlvGlp.sol
> +    }
Let's not add "utility" methods to the farm contract when we could produce the same without too much effort outside of solidity / onchain contract.

Generally we try to minimise contract code when it could be handled in the periphery.

Also, we're not going to run a tricky contract upgrade just to add a view function

2023-03-24 17:46 UTC, farmercarlton commented on pages/farm/[slug]/[id].js
> +    const index = (await contracts.investor.nextPosition()).toNumber() - 1;
This position index could belong to any strategy, not just a GLP one

2023-03-24 17:46 UTC, farmercarlton commented on pages/farm/[slug]/[id].js
> +      const address = await contracts.investor.strategies(i);
We can use `strategy.address` instead of an rpc call

2023-03-24 17:46 UTC, farmercarlton commented on pages/farm/[slug]/[id].js
> +            {['PlutusDAO'].some((p) => p === strategy.protocol) ? (
Let's not plan on having more strategies to add here. I think it's safe to do `strategy.name === 'plvGLP'` here.

2023-03-24 18:19 UTC, voytenko-d commented on contracts/src/StrategyPlutusPlvGlp.sol
> +    }
I got you, yeah makes sense

2023-03-24 18:22 UTC, voytenko-d commented on pages/farm/[slug]/[id].js
> +    const index = (await contracts.investor.nextPosition()).toNumber() - 1;
Yes, it is, I thought about getting the price by all existing strategies, and probably this is what we don't need to

2023-03-24 18:36 UTC, voytenko-d commented on pages/farm/[slug]/[id].js
> +                  {formatNumber(data.strategies.filter((s) => s.address === strategy.address).price, 18) * formatNumber(newLiquidationUsd, 18, 1)}USD
Maybe it looks strange as I took into account that formula: 

price * percent away from liquidation

2023-03-24 21:02 UTC, voytenko-d commented on pages/farm/[slug]/[id].js
> +                  {formatNumber(data.strategies.filter((s) => s.address === strategy.address).price, 18) * formatNumber(newLiquidationUsd, 18, 1)}USD
I got my fault, there is just typo and instead of newLiquidationUsd should be newLiquidationPercent

2023-03-24 21:32 UTC, voytenko-d commented on pages/farm/[slug]/[id].js
> +      const address = await contracts.investor.strategies(i);
Fixed

2023-03-24 21:39 UTC, voytenko-d commented on pages/farm/[slug]/[id].js
> +            {['PlutusDAO'].some((p) => p === strategy.protocol) ? (
Fixed

2023-03-24 21:39 UTC, voytenko-d commented on utils.js
> +          strategyInfo: {...strategy, pricePosition},
Fixed

2023-04-06 13:19 UTC, farmercarlton commented
Closing in favor of https://github.com/rodeofi/rodeo/commit/1709b02cf161541dad3bd4b22b362c1e26d41b70

2023-04-06 13:19 UTC, closed without merging