Feat/rodeo token
rodeofi/rodeo pull request #6
Opened 2023-03-27 14:43 UTC by PfanP

2023-03-28 12:59 UTC, farmercarlton requested changes

2023-03-28 12:59 UTC, farmercarlton commented on contracts/src/RodeoToken.sol
> +        }
Let's not add all this complexity to the tokens contract, let's just mint X initial supply to the deployer and let the wallet do normal transfers to distribute the tokens.

The name of the game should always be: write the least possible solidity and handle the rest in clients/frontends of if really needed for performance/consiseness in periphery/helpers contracts

2023-03-28 12:59 UTC, farmercarlton commented on contracts/src/RodeoToken.sol
> +        address _owner,
Let's use `msg.sender`

2023-03-28 12:59 UTC, farmercarlton commented on contracts/src/RodeoToken.sol
> +        uint8 _decimals,
Let's hard code those 3, we're no looking to deploy multiple of these with different names ;)

2023-03-28 12:59 UTC, farmercarlton commented on contracts/src/RodeoToken.sol
> +contract RodeoToken is ERC20 {
Let's name this just `Token` actually, as we've been trying to avoid using the name "Rodeo" in the codebase in case we rebrand down the road

2023-03-28 12:59 UTC, farmercarlton commented on contracts/src/RodeoToken.sol
> +    uint256 public weeklySupply; // percentage value
Ok, it's a percentage, but in which scale? Would be useful to know if it's 1e18, 1e12? 1e6?

2023-03-28 12:59 UTC, farmercarlton commented on contracts/src/RodeoToken.sol
> +    address public mintAddr;
Let's try and avoid having the data type as part of the variable name when we could use something more descriptive.

Maybe something like `emissionsRecipient`

2023-03-28 12:59 UTC, farmercarlton commented on contracts/src/RodeoToken.sol
> +        require(mintAddr != address(0), "!undefined");
`undefined` doesn't really tell us much about the error case, if we are going to write an error message, we should make it useful.

Also, we've been using solidity v8 errors (`error EmissionsRecipientIsZero()` and `revert EmissionsRecipientIsZero()`) elsewhere in the codebase, we should keep using them ;)

2023-03-28 12:59 UTC, farmercarlton commented on contracts/src/RodeoToken.sol
> +        require(block.timestamp >= lastMintTime + 1 weeks, "Can only mint once per week");
The error message doesn't match the more concise 1-2 word format used elsewhere.

Also, v8 errors :)

2023-03-28 13:11 UTC, PfanP commented on contracts/src/RodeoToken.sol
> +        }
Okay

2023-03-30 13:00 UTC, farmercarlton commented on contracts/src/RodeoToken.sol
> +    event SetWeeklySupply(address indexed owner, uint64 amt, uint64 decay);
Let's call those "Weekly Emissions", supply sounds a bit off here

2023-03-30 13:02 UTC, farmercarlton commented on contracts/src/RodeoToken.sol
> +    constructor(uint256 _initialSupply) ERC20("Token", "TOKEN", 18) ERC20Permit("Token") {
Because it's hardcoded, the name and symbol need to be the ones we actually want to use for the Rodeo token.

So that would be "Rodeo" and "RODEO".

2023-03-30 13:03 UTC, farmercarlton commented on contracts/src/RodeoToken.sol
> +            revert NoMintAddress();
Nice! 👍

2023-03-30 13:09 UTC, farmercarlton commented on contracts/src/RodeoToken.sol
> +        uint256 weeklyAmt = totalSupply * uint256(emissionRate) / MAX_BPS;
Seems like you are missing a crucial detail from my "example" code for this section, we need to be calculating *AND* storing the `lastAmountPerWeek` value as without updating it we'll get a curve that's linear, not exponential.

i.e. 100 - 5% of 100 - 5% of 100 (90) is not the same as 100 - 5% of 100 - 5% of 95 (90.25)

In the first case we only have at most initial / step subtractions, with the other we have theoretically infinite subtractions

2023-03-30 13:10 UTC, farmercarlton commented on contracts/src/RodeoToken.sol
> +    function setWeeklySupply(uint64 _emissionRate, uint64 _decayPerWeek) external auth {
Let's call this `setEmissions`

2023-03-30 13:10 UTC, farmercarlton commented on contracts/src/RodeoToken.sol
> +    function setEmissiontAddr(address _emissionAddr) external auth {
Let's call this `setEmissionsRecipient`

2023-03-30 13:11 UTC, farmercarlton commented on contracts/src/test/Token.t.sol
> +        token.emissionMint();
Can we also check that the `emissionsRecipient` address received the right amount of tokens?

2023-03-30 13:16 UTC, farmercarlton commented on contracts/src/RodeoToken.sol
> +        emit Mint(emissionsRecipient, amtToMint);
Now, this function is not complete, in the specification for this contract we are looking to switch to a fixed % of total supply being minted after X time after deployment (2 years is the current thinking)

So this method needs to switch to minting just a % of current totalSupply once we are past that configured time

2023-03-30 13:16 UTC, farmercarlton commented on contracts/src/RodeoToken.sol
> +        emit Mint(emissionsRecipient, amtToMint);
I think those 2 values (percent and time) should be changable before they become active, but once active we shouldn't be able to change them :)

2023-03-30 14:59 UTC, PfanP commented on contracts/src/RodeoToken.sol
> +    uint64 public emissionRate; // percentage value
100% is MAX_BPS value

2023-03-31 15:29 UTC, farmercarlton commented on contracts/src/RodeoToken.sol
> +    uint256 public emissionRate; // percentage value
Again, if we are going to have a comment, let's make it tell us what is 100%? If it's 1e18 let's write that in there

2023-03-31 15:31 UTC, farmercarlton commented on contracts/src/RodeoToken.sol
> +    uint256 public MAX_BPS = 1e18;
I usually prefer to inline those numbers as I don't really see the big difference versus using a long variable name like `MAX_BPS`

If we are going to keep it though we should make it a `constant` to save on gas. It also probably shouldn't be public.

2023-03-31 15:31 UTC, farmercarlton commented on contracts/src/RodeoToken.sol
> +    constructor(uint256 _initialSupply) ERC20Permit("Rodeo", "RODEO", 18) {
Let's maybe name `_initialSupply` a bit more like the rest of the variables. I would at least just drop the `_`

2023-03-31 15:35 UTC, farmercarlton commented on contracts/src/RodeoToken.sol
> +        lastAmtPerWeek = totalSupply * emissionRate / MAX_BPS;
This update doesn't make sense. `emissionsRate` is a token amount and should be assigned to `lastAmtPerWeek`

We need a separate configuration method for the parameters related to the fixed supply minting past X years

2023-03-31 15:36 UTC, farmercarlton commented on contracts/src/RodeoToken.sol
> +        lastMintTime = block.timestamp;
Setting this doesn't make sense, it means we loose out on the tokens that were meant to be minted since the last time `mintEmissions()` was called

2023-03-31 15:36 UTC, farmercarlton commented on contracts/src/interfaces/IERC5267.sol
> +// SPDX-License-Identifier: MIT
Don't this we need this anymore

2023-03-31 15:36 UTC, farmercarlton commented on contracts/src/interfaces/IERC20Permit.sol
> +// SPDX-License-Identifier: MIT
Let's drop this file until we really need it

2023-03-31 15:37 UTC, farmercarlton commented on contracts/src/test/Token.t.sol
> +        token.emissionMint();
In the tests I mean...

2023-03-31 17:23 UTC, PfanP commented on contracts/src/RodeoToken.sol
> +        lastAmtPerWeek = totalSupply * emissionRate / MAX_BPS;
For what purpose should we keep fixed supply minting past X years?

2023-04-03 14:03 UTC, farmercarlton commented on contracts/src/RodeoToken.sol
> +    function emissionMint() external live {
Let's call this one `mintEmissions`, it sounds more like natural english and lines up better with the existing `_mint` method

2023-04-03 14:22 UTC, farmercarlton requested changes

2023-04-03 14:22 UTC, farmercarlton commented on contracts/src/RodeoToken.sol
> +        paused = true;
Why does it start as paused? I think we don't really need to start it at X time. We should deploy the contract when we are ready for emissions to start, it means less code, less logic and place for error

2023-04-03 14:22 UTC, farmercarlton commented on contracts/src/RodeoToken.sol
> +        paused = true;
If we really wanted to make use of the paused param I would see it pausing transfers, but that's a change that would need to happen in the ERC20 contract and that I don't think is required

2023-04-03 14:22 UTC, farmercarlton commented on contracts/src/RodeoToken.sol
> +    function setEmissions(uint256 _emissionRate, uint256 _decayPerWeek, uint256 _deadline, uint256 _weeklyPercent) external auth {
This method is not updating a bunch of parameters. It's not really "setting emissions" anymore.

How about we call it "configure"?

2023-04-03 14:22 UTC, farmercarlton commented on contracts/src/RodeoToken.sol
> +        deadline = _deadline;
I think I would have liked to see this and the weekly percent configured in a separate method because, like I mentioned, we shouldn't be able to update them after the deadline has passed.

Although the 2 other params don't matter anymore one past `deadline` so you could just add that condition in here

2023-04-03 14:22 UTC, farmercarlton commented on contracts/src/RodeoToken.sol
> +        emit SetEmissions(msg.sender, _emissionRate, _decayPerWeek);
Now we have more arguments, they probably should show up here too

2023-04-03 14:22 UTC, farmercarlton commented on contracts/src/test/Token.t.sol
> +        assertEq(balanceAfter - balanceBefore, 141);
Nice! After we checked it once we don't need to do it for every other test case for the same code path. Just checking the event (or just checking the balance should be enough)

2023-04-03 14:22 UTC, farmercarlton commented on contracts/src/RodeoToken.sol
> +            lastMintTime = block.timestamp;
Now this is problematic because it means we're introducing gaps in the minting / supply, like I explained with the original version of this method you wrote. Every second between the time where minting is available again and the transaction to do so runs, are tokens/time that we can never gain back.

There's 2 solutions here:

1. Instead of setting lastMintTime to the current time, we set it to `lastMintTime + 1 week`, then if we miss a couple weeks, we still get to call mintEmissions a couple times in a row and catch up
2. Or, like I explained, we need to switch our thinking to a more "fluid" way of dealing with numbers. Yes the configured percentage of total supply to mint is for 1 week but we can scale that amount to exactly how much time has elapsed since the last mint. This just makes things simpler, more precise and really makes the caller's life easier (they can call anytime)

2023-04-03 14:22 UTC, farmercarlton commented on contracts/src/test/Token.t.sol
> +import {console} from "./utils/console.sol";
We should remove this import once we're done with it

2023-04-03 14:22 UTC, farmercarlton commented on contracts/src/test/Token.t.sol
> +import {Token} from "../RodeoToken.sol";
This file wasn't renamed to `Token.sol` yet

2023-04-03 14:22 UTC, farmercarlton commented on contracts/src/RodeoToken.sol
> +    uint256 public emissionRate; // percentage value, 1e18 = 100%
Why is this variable separate from every other one?

A good practice is to group the "configuration" variables in one block and then all the "instance/running" variables together (lastAmountPerWeek, lastMintTime)

2023-04-06 12:08 UTC, farmercarlton requested changes

2023-04-06 12:08 UTC, farmercarlton commented on contracts/src/Token.sol
> +        lastMintTime = block.timestamp;
Again, let's not set `lastMintTime` in here because it means we loose emissions!

2023-04-06 12:13 UTC, PfanP commented on contracts/src/Token.sol
> +        lastMintTime = block.timestamp;
Should we set lastMintTime at constructor?

2023-04-12 15:50 UTC, merged