:sparkles: update investActor
rodeofi/rodeo pull request #9
Opened 2023-03-31 02:41 UTC by PfanP

2023-03-31 15:22 UTC, farmercarlton requested changes

2023-03-31 15:22 UTC, farmercarlton commented on contracts/src/InvestorActor.sol
> +        (, address pol, uint256 str, uint256 out,,osha,) = investor.positions(id);
For new positions `osha` will always be 0 because the call to `edit` is what is meant to actually invest the initial `amt` and return how many `sha` were minted

2023-03-31 15:22 UTC, farmercarlton commented on contracts/src/InvestorActor.sol
> +        // Check if it's new position
This comment is helpful but could be a bit more helpful, like `// If new position, amt is position value, else it's difference in rate()

2023-04-06 13:05 UTC, farmercarlton commented on contracts/src/InvestorActor.sol
> +    function _takeAmountFromShare(uint256 id) internal view returns (uint256 oout, uint256 omat) {
This is not `taking` anything I think, it would benefit from looking more like a view function. Naming it `_getOutsetAndValue()` might make more sense?

2023-04-11 16:57 UTC, PfanP commented on contracts/src/InvestorActor.sol
> +            bas = int256(strategy.rate(uint256(sha)));
Oh ok! I missed that.  previous implementation was right

2023-04-12 15:54 UTC, farmercarlton commented on contracts/src/StrategyUSDCTest.sol
> +contract StrategyUSDCTest is Strategy {
Because this contract is only used in tests, we should move it to the `src/test/mocks/` folder and rename it `MockStrategyRealistic` to match the naming of other mocks.

(USDC shouldn't be in the name when really it can take any token as argument and use that)

2023-04-12 16:03 UTC, farmercarlton commented on contracts/src/InvestorActor.sol
> +                int256(oamt) - int256(strategy.rate(uint256(sha)));
Now that I think about it some more, we need to be careful with the change to the amount we return here.

The goal is for the "amount" on a position to only ever represent the $ value that a user deposited into a strategy, this means we can't count the value that a borrow, then invested, generated.

At the end of the day, when the user closed a position, we need to be able to do `value - borrow - amount = yield/profit/roi`

2023-04-27 23:34 UTC, closed without merging